matrix:
  include:
    - language: go
      go: "1.10"

    - language: node_js
      node_js: node
      install: npm --prefix ./web install ./web
      script: npm --prefix ./web test
    
deploy:
  provider: script
  script: docker-compose push

    