git:
  depth: 1
  submodules: false

jobs:
  include:
    - stage: test
      language: go
      go: "1.10"
      before_install: 
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      install: 
        - dep ensure

    - language: node_js
      node_js: node
      install: npm --prefix ./web install ./web
      script: npm --prefix ./web test

    - stage: deploy
      if: branch IN (master, development)
      provider: script
      script: 
        - echo test