matrix:
  include:
    - language: go
      go: "1.10"

    - language: node_js
      node_js: node
      install: npm --prefix ./frontend install ./frontend
      script: npm --prefix ./frontend test