env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

matrix:
  include:
    - language: go
      go: "1.10"
      before_install:                                                                 
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
        - dep ensure

    - language: node_js
      node_js: node
      install: npm --prefix ./web install ./web
      script: npm --prefix ./web test
    
deploy:
  provider: script
  script: docker-compose build && docker-compose push
  on:
    branch: development

    