jobs:
  include:
    - stage: "Test"
      name: "go"
      language: go
      go: "1.10"
      before_install: 
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      install: 
        - dep ensure -vendor-only
    - language: node_js
      node_js: node
      install: npm --prefix ./web install ./web
      script: npm --prefix ./web test
      name: "nextjs"
    - stage: "Deploy"
      name: "deploy to server"
      script: echo Test