jobs:
  include:
    - stage: "Test"
      name: "go"
      language: go
      go: "1.11"
      script: go test
      env:
        - GO111MODULE=on

    - language: node_js
      node_js: node
      install: npm --prefix ./web install ./web
      script: npm --prefix ./web test
      name: "nextjs"

    - stage: "Deploy"
      script: skip
      language: generic
      if: branch IN (master, development) # and tag IS present
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_531129a75a03_key -iv $encrypted_531129a75a03_iv -in secrets.tar.enc -out secrets.tar -d
        - mkdir $DOCKER_CERT_PATH
        - tar xvf secrets.tar -C $DOCKER_CERT_PATH
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      after_deploy:
        - rm -rf $DOCKER_CERT_PATH
      deploy:
        provider: script
        script: bash ./scripts/deploy.sh
      env:
        - DOCKER_COMPOSE_VERSION=1.21.2
        - DOCKER_TLS_VERIFY=1
        - DOCKER_HOST=tcp://scores.network:2376
        - DOCKER_CERT_PATH=certs
