version: '3.6'

services:
  frontend:
    build: ./web
    ports:  
      - '3000:3000'
    
  backend:
    user: scores
    build: 
      context: .
      dockerfile: ./cmd/web/Dockerfile
      
    ports:
      - '8080:8080'
    volumes:
      - '~/data:/srv/scores'
    
  scrape:
    depends_on:
      - 'backend'
    build: 
      context: .
      dockerfile: ./cmd/terminal/Dockerfile
