version: '3.6'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './nginx-config:/etc/nginx/conf.d:ro'
    logging:
      driver: none


  frontend:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - './web:/web'

  backend:
    ports:
      - '8080:8080'
      - '40000:40000'
    environment:
      - GIN_MODE=debug
      - BACKEND_URL=http://localhost
      - APP_ENV=debug
    build:
      dockerfile: ./cmd/web/Dockerfile.dev
    volumes:
      - './data:/srv/scores'
    security_opt:
      - seccomp:unconfined