version: "3.6"

services:
  frontend:
    build:
      dockerfile: ./dockerfiles/prod/frontend
      context: .

  backend:
    build:
      dockerfile: ./dockerfiles/prod/backend
      context: .
    volumes:
      - "~/data/api:/srv/scores"
    environment:
      - GIN_MODE=release
      - BACKEND_URL=https://scores.network
      - APP_ENV=production

  mariadb:
    image: mariadb:latest
    volumes:
      - "~/data/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test

  elasticsearch:
    volumes:
      - "~/data/elasticsearch:/usr/share/elasticsearch/data"
