version: "3.6"

services:
  frontend:
    build:
      dockerfile: ./dockerfiles/dev/frontend
      context: .
    # volumes:
    #   - ".:/scores"

  backend:
    build:
      dockerfile: ./dockerfiles/dev/backend
      context: .
    volumes:
      - "./data/backend:/srv/scores"
    command:
      - "-connection"
      - "root:test@tcp(mariadb)/scores?charset=utf8mb4&parseTime=true"
      - "-provider"
      - "mysql"
      - "-goauth"
      - "/srv/scores/client_secret.json"
    environment:
      - GIN_MODE=debug
      - BACKEND_URL=http://localhost
      - APP_ENV=debug
    security_opt:
      - seccomp:unconfined
    ports:
      - "127.0.0.1:40000:40000"

  envoy:
    build:
      dockerfile: "./dockerfiles/dev/envoy"
      context: .
    volumes:
      - "./certs:/usr/share/letsencrypt/scores.network"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8001:8001"

  mariadb:
    image: "mariadb:latest"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"

  elasticsearch:
    build:
      dockerfile: "./dockerfiles/deploy/elasticsearch"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build:
      dockerfile: "./dockerfiles/deploy/kibana"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    build:
      dockerfile: "./dockerfiles/deploy/logstash"
      context: .
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
