version: '3.6'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './nginx-config:/etc/nginx/conf.d:ro'

  frontend:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - './web:/web'

  backend:
    environment:
      - GIN_MODE=debug
      - BACKEND_URL=http://localhost
      - APP_ENV=debug
    build:
      dockerfile: ./cmd/web/Dockerfile.dev
    volumes:
      - './data:/srv/scores'