version: "3.6"

services:
  frontend:
    build:
      dockerfile: ./dockerfiles/deploy/frontend
      context: .

  backend:
    build:
      dockerfile: ./dockerfiles/deploy/backend
      context: .
    volumes:
      - "~/data/api:/srv/scores"
    environment:
      - GIN_MODE=release
      - BACKEND_URL=https://scores.network
      - APP_ENV=production

  envoy:
    build:
      dockerfile: ./dockerfiles/deploy/frontend
      context: .
    volumes:
      - "/etc/letsencrypt/live/scores.network:/certs"

  mariadb:
    image: mariadb:latest
    volumes:
      - "~/data/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test

  elasticsearch:
    volumes:
      - "~/data/elasticsearch:/usr/share/elasticsearch/data"
