name: Docker Push and Deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run tests
        run: ./scripts/test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Docker push
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PW}}
        run: ./scripts/docker-push.sh

      - name: Deploy
        env:
          DEPLOY_HOST: ${{secrets.DOCKER_DEPLOY_URL}}
        run: ./scripts/deploy.sh

      - name: Cleanup
        if: ${{ always() }}
        run: ./scripts/clean.sh
